# Third-party lossy codecs (#13), fetched from GitHub at configure time:
#
#   CDREADER_WITH_OPUS    libopus  (BSD-3-Clause)  -> "opus" format (Ogg Opus)
#   CDREADER_WITH_VORBIS  libogg + libvorbis (BSD-3-Clause) -> "vorbis" format (Ogg Vorbis)
#
# Both are ON by default; turn them OFF for an offline build (the formats are
# then simply not available). Included before the project's warning flags are
# set, so that /W4 / -Wpedantic do not apply to the third-party code; its own
# warnings are silenced as well, they are not ours to fix.
#
# Defines cdreader_codecs, an INTERFACE target carrying the libraries and the
# CDREADER_HAVE_OPUS / CDREADER_HAVE_VORBIS definitions.

option(CDREADER_WITH_OPUS "Ogg Opus output (fetches libopus from GitHub)" ON)
option(CDREADER_WITH_VORBIS "Ogg Vorbis output (fetches libogg and libvorbis from GitHub)" ON)

set(CDREADER_OPUS_TAG v1.5.2 CACHE STRING "libopus release tag")
set(CDREADER_OGG_TAG v1.3.5 CACHE STRING "libogg release tag")
set(CDREADER_VORBIS_TAG v1.3.7 CACHE STRING "libvorbis release tag")
mark_as_advanced(CDREADER_OPUS_TAG CDREADER_OGG_TAG CDREADER_VORBIS_TAG)

add_library(cdreader_codecs INTERFACE)

if(NOT CDREADER_WITH_OPUS AND NOT CDREADER_WITH_VORBIS)
  return()
endif()

include(FetchContent)
enable_language(C)

# No warnings from third-party code; with GCC / Clang it is also optimized in
# Debug builds (the encoders are slow at -O0, which makes the tests slow;
# MSVC's Debug run-time checks cannot be combined with /O2).
function(cdreader_quiet_third_party target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /w)
  else()
    target_compile_options(${target} PRIVATE -w $<$<CONFIG:Debug>:-O2>)
  endif()
endfunction()

# --- libopus: built with its own CMake project (it selects the SIMD code) ----
if(CDREADER_WITH_OPUS)
  FetchContent_Declare(opus
    GIT_REPOSITORY https://github.com/xiph/opus.git
    GIT_TAG ${CDREADER_OPUS_TAG}
    GIT_SHALLOW TRUE
  )
  set(OPUS_BUILD_SHARED_LIBRARY OFF)
  set(OPUS_BUILD_TESTING OFF)
  set(OPUS_BUILD_PROGRAMS OFF)
  set(OPUS_INSTALL_PKG_CONFIG_MODULE OFF)
  set(OPUS_INSTALL_CMAKE_CONFIG_MODULE OFF)
  set(OPUS_STATIC_RUNTIME ON)  # same MSVC runtime as ours (CMAKE_MSVC_RUNTIME_LIBRARY)
  set(OPUS_FORTIFY_SOURCE OFF) # only warns in unoptimized (Debug / sanitizer) builds
  # libopus' CMake would otherwise force CMAKE_BUILD_TYPE=Release into the
  # cache when no build type is given; keep that decision with the user.
  set(__opus_buildtype INCLUDED)
  FetchContent_MakeAvailable(opus)
  cdreader_quiet_third_party(opus)
  target_link_libraries(cdreader_codecs INTERFACE opus)
  target_compile_definitions(cdreader_codecs INTERFACE CDREADER_HAVE_OPUS=1)
endif()

# --- libogg + libvorbis(enc): their CMake projects are too old for current
# CMake (cmake_minimum_required 2.8.12), so the libraries are built here from
# the fetched sources. SOURCE_SUBDIR points to a directory without a
# CMakeLists.txt, so FetchContent only downloads them.
if(CDREADER_WITH_VORBIS)
  FetchContent_Declare(ogg
    GIT_REPOSITORY https://github.com/xiph/ogg.git
    GIT_TAG ${CDREADER_OGG_TAG}
    GIT_SHALLOW TRUE
    SOURCE_SUBDIR no-cmake
  )
  FetchContent_Declare(vorbis
    GIT_REPOSITORY https://github.com/xiph/vorbis.git
    GIT_TAG ${CDREADER_VORBIS_TAG}
    GIT_SHALLOW TRUE
    SOURCE_SUBDIR no-cmake
  )
  FetchContent_MakeAvailable(ogg vorbis)

  # <ogg/config_types.h> is generated by libogg's build system.
  set(_ogg_generated ${CMAKE_CURRENT_BINARY_DIR}/ogg-generated)
  file(WRITE ${_ogg_generated}/ogg/config_types.h.tmp
"#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__
/* Generated by cdreader (cmake/Codecs.cmake) */
#include <stdint.h>
typedef int16_t ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t ogg_int64_t;
typedef uint64_t ogg_uint64_t;
#endif
")
  configure_file(${_ogg_generated}/ogg/config_types.h.tmp ${_ogg_generated}/ogg/config_types.h COPYONLY)

  add_library(cdreader_ogg STATIC
    ${ogg_SOURCE_DIR}/src/bitwise.c
    ${ogg_SOURCE_DIR}/src/framing.c
  )
  target_include_directories(cdreader_ogg PUBLIC ${ogg_SOURCE_DIR}/include ${_ogg_generated})
  cdreader_quiet_third_party(cdreader_ogg)

  set(_vorbis_sources
    analysis.c bitrate.c block.c codebook.c envelope.c floor0.c floor1.c info.c
    lookup.c lpc.c lsp.c mapping0.c mdct.c psy.c registry.c res0.c sharedbook.c
    smallft.c synthesis.c vorbisenc.c window.c
  )
  list(TRANSFORM _vorbis_sources PREPEND ${vorbis_SOURCE_DIR}/lib/)
  add_library(cdreader_vorbis STATIC ${_vorbis_sources})
  target_include_directories(cdreader_vorbis
    PUBLIC ${vorbis_SOURCE_DIR}/include
    PRIVATE ${vorbis_SOURCE_DIR}/lib)
  target_link_libraries(cdreader_vorbis PUBLIC cdreader_ogg)
  if(MSVC)
    target_compile_definitions(cdreader_vorbis PRIVATE _CRT_SECURE_NO_WARNINGS _CRT_NONSTDC_NO_DEPRECATE)
  endif()
  if(NOT WIN32)
    target_link_libraries(cdreader_vorbis PUBLIC m)
  endif()
  cdreader_quiet_third_party(cdreader_vorbis)

  target_link_libraries(cdreader_codecs INTERFACE cdreader_vorbis)
  target_compile_definitions(cdreader_codecs INTERFACE CDREADER_HAVE_VORBIS=1)
endif()
